import type { Metadata } from "next";
import { ContentLayout } from "../content-layout";
export const metadata: Metadata = { title: "Política de privacidad", description: "Política de privacidad, almacenamiento local, cookies, analítica y publicidad de Modo Carrera DT.", alternates: { canonical: "/privacidad" } };
export default function PrivacyPage() { return <ContentLayout eyebrow="INFORMACIÓN LEGAL" title="POLÍTICA DE PRIVACIDAD" intro="Qué datos utiliza Modo Carrera DT y cómo podés controlar tu información.">
  <section><h2>Partidas y datos del juego</h2><p>Modo Carrera DT no requiere crear una cuenta. Las partidas se guardan en el almacenamiento local de tu navegador para que puedas continuar en el mismo dispositivo. Podés eliminarlas desde las opciones del juego o borrando los datos del sitio en tu navegador.</p></section>
  <section><h2>Analítica y publicidad</h2><p>El sitio utiliza servicios de Google para medir visitas y, cuando corresponda, mostrar publicidad. Google y otros proveedores externos pueden utilizar cookies para publicar anuncios basados en visitas anteriores a este u otros sitios. Google puede usar cookies publicitarias para que sus socios muestren anuncios personalizados.</p><p>Podés administrar o desactivar la personalización desde <a href="https://adssettings.google.com/" rel="external">Configuración de anuncios de Google</a>. También podés controlar cookies y almacenamiento desde tu navegador.</p></section>
  <section><h2>Información técnica y terceros</h2><p>El proveedor de alojamiento puede registrar información técnica necesaria para operar y proteger el servicio, como dirección IP, tipo de navegador, fecha, ruta solicitada y errores. No vendemos datos personales. Los enlaces externos tienen sus propias políticas de privacidad.</p></section>
  <section><h2>Contacto y cambios</h2><p>Podés consultar sobre privacidad desde la página de contacto. Esta política puede actualizarse cuando cambien el juego, la legislación aplicable o los servicios utilizados. Última actualización: 16 de septiembre de 2026.</p></section>
 </ContentLayout>; }
