import type { Metadata } from "next";
import { ContentLayout, PageEnd } from "../content-layout";

export const metadata: Metadata = { title: "Guías del juego", description: "Guías originales de Modo Carrera DT: tácticas, mercado, ascenso, carrera de jugador y decisiones narrativas.", alternates: { canonical: "/guias" } };

export default function GuidesPage() {
  return <ContentLayout eyebrow="GUÍAS ORIGINALES" title="ENTENDÉ EL JUEGO. CONSTRUÍ TU HISTORIA." intro="Una guía completa para tomar mejores decisiones sin quitarle al azar lo que hace única a cada carrera.">
    <section id="dt"><p className="section-label">01 · CARRERA DE DIRECTOR TÉCNICO</p><h2>Del primer contrato a la gloria</h2><p>La carrera de DT comienza con una reputación baja y ofertas de clubes que aceptan apostar por un entrenador desconocido. Cada temporada tiene un objetivo institucional: permanecer, alcanzar el Reducido, ascender, clasificar a una copa o salir campeón. Cumplirlo sostiene el contrato y abre mercados más ambiciosos; fallar puede terminar el ciclo.</p><p>Antes de competir analizá las tres líneas del plantel. Una defensa débil no se corrige necesariamente atacando más: una formación equilibrada y un refuerzo compatible pueden ser más valiosos que el nombre más llamativo. La táctica influye, pero nunca elimina la incertidumbre de un partido.</p><h3>Claves para dirigir</h3><ul><li>Elegí el enfoque según las fortalezas reales del plantel.</li><li>No ignores la presión: afecta el rendimiento y el desenlace de eventos.</li><li>Los refuerzos se evalúan después de varios partidos, no al firmar.</li><li>La relación con la dirigencia y el respeto del vestuario pueden salvar un mal momento.</li></ul></section>
    <section id="jugador"><p className="section-label">02 · CARRERA DE JUGADOR</p><h2>De Primera D a Primera</h2><p>Todo futbolista empieza en Primera D. La titularidad depende de la media, el estado físico, la confianza del entrenador y el rendimiento reciente. Entrenar Definición favorece el gol, Técnica ayuda a participar del juego y Físico permite sostener más minutos.</p><p>Una gran temporada puede producir una oferta de la categoría siguiente, aunque renovar también puede ser una buena decisión cuando todavía falta continuidad. Llegar a Primera no termina la carrera: podés seguir compitiendo hasta elegir el retiro o alcanzar la edad límite de tu posición.</p><h3>Cómo crecer</h3><ul><li>Priorizá continuidad antes que saltos demasiado grandes.</li><li>La valoración media importa más que un único partido brillante.</li><li>Una decisión narrativa puede cambiar confianza, físico, reputación o forma.</li><li>Las expulsiones provocadas por eventos también pueden dejarte suspendido.</li></ul></section>
    <section id="ascenso"><p className="section-label">03 · ASCENSOS Y COPAS</p><h2>Cada categoría exige algo distinto</h2><p>Primera C y Primera B castigan la irregularidad: una racha corta puede definir el acceso al Reducido. El Federal A suma el desafío de los viajes y rivales del interior. En Primera Nacional aumenta la presión por ascender y en la Liga Profesional aparecen objetivos continentales.</p><p>La Copa Argentina ofrece una ruta alternativa hacia un título y puede clasificar al campeón a la Libertadores siguiente. En partidos eliminatorios no existe margen para administrar la tabla: la decisión táctica resuelve una noche completa.</p></section>
    <section id="eventos"><p className="section-label">04 · EVENTOS Y PROBABILIDADES</p><h2>No existe una opción siempre correcta</h2><p>Los eventos representan vestuario, dirigencia, prensa, hinchada, arbitrajes y situaciones propias del fútbol argentino. Cada alternativa contiene resultados positivos y negativos. La personalidad del entrenador, la presión del momento o la confianza del jugador pueden modificar las probabilidades.</p><p>Una decisión conservadora suele reducir el riesgo inmediato, pero puede costar respeto. Una respuesta audaz puede unir al grupo o agrandar la crisis. Leé el contexto, observá los indicadores y aceptá que una buena decisión también puede salir mal: administrar esa consecuencia es parte de la carrera.</p></section>
    <PageEnd />
  </ContentLayout>;
}
